log:
  level: info
record: false
license:
  host: http://127.0.0.1
  port: 2244
source:
  cap: 20
  grpc:
    host: 0.0.0.0
    port: 50051
games:
  skiing:
    tiltAngle: 20 # 倾斜角度，单位度，建议配置15-25
    shoulderWidth: 0.2 # 肩膀宽度，单位米，建议配置0.2-0.3
    minElbowAngle: 80 # 最小手肘角度(用于识别游戏开始动作)，单位度，建议配置>80
    maxElbowAngle: 130 # 最大手肘角度(用于识别游戏开始动作)，单位度，建议配置<130
    jumpKneeAngle: 50  # 跳跃的膝盖角度，单位度，建议配置>50
rules:
  A:
    handHightHead: 0 #手高于头的距离，建议 0～0.1
    feetThanHip: 0   #双脚大于胯部的距离，建议 0～0.1
  B:
    feetHeight: 0.1 #双脚之间的高度差，建议 0.2
    leftAndRightFeetXY: 0.3 #左右脚之间的XY 上的位移，建议 0.2
    rightHandThanHeadXYZ: 0.3 #右手和头的三维空间距离，建议 0.3
  C:
    leftHandThanHeadZ: 0.15 #左手和头的高度距离，建议 0.2
  D:
    handAndTipToeDistance: 0.4 #双手和双脚三维空间的距离，建议 0.2
    headAndHipDistanceZ: 0.5 #头和臀部在Z 轴上的空间距离，建议 0.1
  greet:
    elbowAngle: 100 #手肘的角度，建议 100
    handMoveDistanceXZ: 0.15 #手在 XZ 二维平面的移动距离，建议 0.15
  raiseRightHand:
    handThanHeadZ: 0.1 #手（Z方向）高于头的距离，建议 0.1～0.2
  leftRightSlide:
    handMoveDistanceX: 0.1 #在X轴的移动距离，建议 0.1
    handToShoulderXZ: 0.2 #手和肩膀在XZ上的绝对值距离，建议 0.1
  upSlide:
    handMoveDistanceY: 0.02 #在Y轴的移动距离，建议 0.02
    handMoveDistanceZ: 0.03 #在Z轴的移动距离，建议 0.03
    elbowAngle: 110   #手肘的角度，建议 110
    handToShoulderZ: 0.05 #手和肩膀在YZ上的绝对值距离，建议 0.05
  downSlide:
    handMoveDistanceX: 0.1 #在X轴的移动距离，不应该移动太大距离建议, 0<x<0.1
    handMoveDistanceY: 0.1 #在Y轴的移动距离，建议 0.1
    handMoveDistanceZ: 0.20 #在Z轴的移动距离，建议 0.2
    elbowAngle: 20   #手肘的角度，建议 20
    handToHipZ: 0.2 #手和肩膀在YZ上的绝对值距离，建议 0.2
  leftRightTilt:
    tiltAngle: 20 # 倾斜角度，单位度，建议配置15-25
    shoulderWidth: 0.2 # 肩膀宽度，单位米，建议配置0.2-0.3
  elbowBend:
    minAngle: 80 # 最小手肘角度(用于识别游戏开始动作)，单位度，建议配置>80
    maxAngle: 130 # 最大手肘角度(用于识别游戏开始动作)，单位度，建议配置<130
  squat:
    kneeAngle: 100  # 跳跃的膝盖角度，单位度，建议配置>50
  jump:
    kneeHeight: 0.05  # 双脚离地高度，建议配置>0.05
  handsCross:
    leftMinCalculate: 90
    leftMaxCalculate: 130
    rightMinCalculate: 90
    rightMaxCalculate: 130