source:
  cap: 10
  grpc:
    host: 0.0.0.0
    port: 50051

games:
  skiing:
    tiltAngle: 20 # 倾斜角度，单位度，建议配置15-25
    shoulderWidth: 0.2 # 肩膀宽度，单位米，建议配置0.2-0.3
    minElbowAngle: 80 # 最小手肘角度(用于识别游戏开始动作)，单位度，建议配置>80
    maxElbowAngle: 130 # 最大手肘角度(用于识别游戏开始动作)，单位度，建议配置<130
    jumpKneeAngle: 50  # 跳跃的膝盖角度，单位度，建议配置>50
rules:
  A:
    handHightHead: 0 #手高于头的距离，建议 0～0.1
    feetThanHip: 0   #双脚大于胯部的距离，建议 0～0.1
  B:
    feetHeight: 0.2 #双脚之间的高度差，建议 0.2
    leftAndRightFeetXY: 0.2 #左右脚之间的XY 上的位移，建议 0.2
    rightHandThanHeadXYZ: 0.3 #右手和头的三维空间距离，建议 0.3
  C:
    leftHandThanHeadZ: 0.2 #左手和头的高度距离，建议 0.2
  D:
    handAndTipToeDistance: 0.2 #双手和双脚三维空间的距离，建议 0.2
    headAndHipDistanceZ: 0.2 #头和臀部在Z 轴上的空间距离，建议 0.2
  greet:
    elbowAngle: 100 #手肘的角度，建议 100
    handMoveDistanceXZ: 0.15 #手在 XZ 二维平面的移动距离，建议 0.15
  raiseRightHand:
    handThanHeadZ: 0.1 #手（Z方向）高于头的距离，建议 0.1～0.2
  leftSlide:
    handMoveDistanceX: 0 #在X轴的移动距离，建议 0.2
    handToShoulderXZ: 0.05 #手和肩膀在XZ上的绝对值距离，建议 0.05
  leftRightTilt:
    tiltAngle: 20 # 倾斜角度，单位度，建议配置15-25
    shoulderWidth: 0.2 # 肩膀宽度，单位米，建议配置0.2-0.3
  elbowBend:
    minAngle: 80 # 最小手肘角度(用于识别游戏开始动作)，单位度，建议配置>80
    maxAngle: 130 # 最大手肘角度(用于识别游戏开始动作)，单位度，建议配置<130
  squat:
    kneeAngle: 50  # 跳跃的膝盖角度，单位度，建议配置>50

    