//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/MInputSystem/MultiPlayer/InputSystem/playerAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""playerAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ac4c2fc0-6810-4ab3-a4b9-4eba75226bd2"",
            ""actions"": [
                {
                    ""name"": ""ArmToForward"",
                    ""type"": ""Button"",
                    ""id"": ""f25e1dfb-ec28-4d6b-b137-3d5c0172206a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToBack"",
                    ""type"": ""Button"",
                    ""id"": ""d16bd971-0e6c-4c45-adea-d2edc5db67aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""3de286f9-ab52-4bfb-8139-853ec736204b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToRight"",
                    ""type"": ""Button"",
                    ""id"": ""58be3caf-bdfd-47b3-abb4-e5d6270a6098"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HandsCross"",
                    ""type"": ""Button"",
                    ""id"": ""adbc6332-ae8d-4f9e-8440-e03a0074d07f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RaiseOnHand"",
                    ""type"": ""Button"",
                    ""id"": ""d66fcbca-9731-4f74-964a-b265d716a4be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeepSquat"",
                    ""type"": ""Button"",
                    ""id"": ""e75bba22-e997-4934-a40a-5c73bb2ad1ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Butterfly"",
                    ""type"": ""Button"",
                    ""id"": ""558793dc-9658-4056-b528-91bbcaeda784"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastRun"",
                    ""type"": ""Button"",
                    ""id"": ""ec57c758-eaa9-4c0a-8085-89d581bdd33d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Freestyle"",
                    ""type"": ""Button"",
                    ""id"": ""7b15055b-e863-4211-8791-06b616bd76b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""73f707bd-8ced-4036-b936-ed8c5b8cfa5f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cbab5cde-cdca-4343-9475-c2c8ee9abf0f"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abf6ddbc-d71b-4f47-86a4-57930f03a7cc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f5d7e79-436b-40b1-b002-278d832739c6"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af49d496-ef64-4178-8224-579362c9f008"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c491115-c5ae-40db-9b15-ff518d4473a2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5483e18d-4ecb-487c-94c4-1d8f7d2020c8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0051198d-385e-4032-982a-6d135b2ad1aa"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eadd23ab-743f-4330-8230-4f7f43382770"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42334978-9e94-4495-a18b-f36c98466bb0"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandsCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97804446-30dc-407d-a211-0fdb32a44fd6"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandsCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e991cfd9-6f29-4ff4-aab9-5df0c390695f"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RaiseOnHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68f00147-1633-424d-a6ba-a4bd56a10b87"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RaiseOnHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e6af5ba-40de-4e0f-aa4b-bf970917d9a7"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Freestyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6deebf28-6df2-4010-a0c4-50e13dfccc03"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Freestyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b290eea2-4f5d-471b-916c-57b69b37670a"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up/Down/Left/Right Arrow"",
                    ""id"": ""0898cc80-cc05-4cc6-af04-992177383562"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""2736c1fa-e633-4098-8563-ecd891c35bcf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7435a448-37d5-4e55-a202-174403abd932"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""518d099b-3ef3-4d06-923f-d88a02d9756e"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f009327a-14cb-4399-8fd6-cdb30e86ecd4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""80fa5b00-5622-4aa0-a60e-6b24b2a845ce"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeepSquat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29c793c-df20-4fe6-9c7b-49d2ef6d831a"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DeepSquat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16e18075-1528-4dda-97e6-b3ccc36381ec"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Butterfly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b8a93bb-9430-4f9d-a9a3-0dc5c3db1c34"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Butterfly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11a6d238-8dc9-4982-a563-ea4bb03daac0"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a275e5-f3b4-47f1-99bd-913b9dae8a7a"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Moat"",
            ""id"": ""2ca84d4f-4cdc-4219-b3b3-05c3d999a309"",
            ""actions"": [
                {
                    ""name"": ""ArmToForward"",
                    ""type"": ""Button"",
                    ""id"": ""1c7b9805-30e0-480b-86ce-6648a8d2b47d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToBack"",
                    ""type"": ""Button"",
                    ""id"": ""b9aa6dc2-5eb1-4bd1-83f2-ddee74f1bf77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""5ad76abe-af6b-4cbe-b358-edb67500769e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ArmToRight"",
                    ""type"": ""Button"",
                    ""id"": ""f2488da6-24c5-4e46-9fa9-3f1981431165"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HandsCross"",
                    ""type"": ""Button"",
                    ""id"": ""40e86ada-46dd-4499-bf5c-979da70b154d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RaiseOnHand"",
                    ""type"": ""Button"",
                    ""id"": ""051267eb-6947-40a5-9cfe-9a49536b8afb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PoseA"",
                    ""type"": ""Button"",
                    ""id"": ""ab84544f-8f0d-4912-ad8c-442dfd42b048"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PoseB"",
                    ""type"": ""Button"",
                    ""id"": ""32090f30-9a8f-4547-b48e-1298a2005da1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PoseC"",
                    ""type"": ""Button"",
                    ""id"": ""2182a711-49c2-49b7-abc7-2a4ceb23d303"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PoseD"",
                    ""type"": ""Button"",
                    ""id"": ""c85dc76a-173d-49d4-b4f4-34209b81d187"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHandDrawCircle"",
                    ""type"": ""Button"",
                    ""id"": ""9d1cbbb3-ccfd-48fe-b31e-5fb7e90732c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHandDrawCircle"",
                    ""type"": ""Button"",
                    ""id"": ""6002e0bc-a1a5-4f50-aed9-b543195aca3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideUp"",
                    ""type"": ""Button"",
                    ""id"": ""54458802-5ce4-4726-80b2-5c9bfcaf64b6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideDown"",
                    ""type"": ""Button"",
                    ""id"": ""12890557-2704-46bf-8814-f3bb234662fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideLeft"",
                    ""type"": ""Button"",
                    ""id"": ""d58c2407-fc71-4fc7-af9e-c60bcf3cdd8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlideRight"",
                    ""type"": ""Button"",
                    ""id"": ""fd9c1a73-2388-4570-a9cf-44bed7f3d337"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f0622633-98d6-4e02-9b32-a447dfb69178"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SmallSquat"",
                    ""type"": ""Button"",
                    ""id"": ""10c9f5af-7478-46bc-a5f7-7c4c6f95a869"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Butterfly"",
                    ""type"": ""Button"",
                    ""id"": ""e7ceb79b-264e-4868-84a5-95c15956bcb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FastRun"",
                    ""type"": ""Button"",
                    ""id"": ""fac1f49b-3695-4bf5-a77d-5b8bfeb09f7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeanToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""4662cbf8-d821-4f4c-b243-b4b250ef1397"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeanToRight"",
                    ""type"": ""Button"",
                    ""id"": ""d9f33575-5b0d-4017-950e-76aa799d68e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Applaud"",
                    ""type"": ""Button"",
                    ""id"": ""9072032a-e4f3-48d9-9ba3-576a8c00cce8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Waving"",
                    ""type"": ""Button"",
                    ""id"": ""1c66e6c9-48c6-40a2-b4d3-00514ae709da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""9015693d-963a-4a90-8769-2401971b24e2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""de1ef8c4-fbcc-4c1a-a139-58556f84e8cf"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8256d03e-42c7-4691-80cb-7a30f1e957b4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToForward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67d7bc4a-a7d0-431a-b425-2564b316db59"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d21befc9-75e0-43b3-bff6-2c9a56ffe7ec"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffed2b1d-e3b9-49b7-9156-6c3576b33bd9"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb414d3f-410c-47a1-b3e9-629b219fd6ce"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57957f42-9c0a-4447-9f2a-bfba58b98f48"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b727e1fe-c756-45f2-9331-b48a5a644d29"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ArmToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea8dce99-45db-4c3d-90d3-165569f6c462"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandsCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58099c1d-6a67-4fb1-a120-5e05cc4369ec"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HandsCross"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbffa7b7-dd3f-4fc0-9a6f-0771a02ecd1d"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RaiseOnHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cbf898a-58af-448d-af1f-cbdb4ddc798d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RaiseOnHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa63528e-d228-4d21-ab41-8c6e987b041a"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c99e801-9563-4f80-9036-65e894d2e4c9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseA"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e4c270-88f9-42ab-b49a-b51cbfb920b7"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1411275b-6fdd-4bd7-92fe-1106eef3ee5c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae11a6b4-e329-421e-9b43-7203d0cf3016"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""695c5c1b-627f-4e12-a47f-93f9def3a7db"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseC"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d082aa41-753c-45f1-8cf5-2be7ac5e601a"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da107908-138c-49c4-b952-36ec0af7ac58"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PoseD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb3c933c-1587-4520-acdf-161b71d83b5f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandDrawCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa3d48ad-4a21-4bc7-acbd-f632d81a4af8"",
                    ""path"": ""<Keyboard>/leftBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHandDrawCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06d891d0-b9e5-49c9-b80b-bf4e03ed28ca"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHandDrawCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a56d5a4-3dd6-47dd-8a8a-f8b814ea0f51"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHandDrawCircle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c41bb312-febb-440e-bba8-8072532b0fda"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71b6156d-427f-4cca-a66a-36d66702f723"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26dc5e7e-2a2d-4da7-ab29-9d124df5a316"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""565c4eab-51bb-4eaf-a890-220f6ea6a988"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0febf89f-9cd8-4150-a5a3-fb83cd648b6a"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71898035-b9fa-4a54-92ee-4d13e147b495"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4a1ccab-91db-42f7-88af-63885bb593a6"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc801c2a-7824-4032-9bf4-f239cfe752f1"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlideRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""968a1871-f4b6-43f9-939b-5618919a3be7"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd1dff0e-09e3-4a94-b5b1-10b86bfd6deb"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b982fd0-f0d4-429b-84de-42fc15830b56"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SmallSquat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22280cef-e3c4-41fd-b02f-c637b7fc5b4a"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SmallSquat"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5339a86d-9423-4482-8d75-32ffddeab441"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b505da5-4797-4f18-9053-72a82e39eaab"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FastRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2911192-af2d-4065-9917-90b2e3650d1b"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeanToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25652571-6f02-409d-a622-2863b3e4a7a9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeanToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78947169-9531-43d1-bb37-7a7b803cc63a"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeanToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""588aaa8a-dc77-434d-a420-9a77b62612c0"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeanToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37bd2a62-2927-4f8f-be33-b1be7fc5e71f"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Butterfly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0096c33f-6efc-483e-8485-aee12edcc7a7"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Butterfly"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c8462a25-93cf-4576-ad18-dad6fa4a505e"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Applaud"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""858a4d00-6c94-43d9-a772-491bf4a187bc"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Applaud"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb8ba28b-6b45-4bbb-8e80-7233a72b6aeb"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Waving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5ffb11f-d92c-476e-8d4c-88c0ece31cfc"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Waving"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""743a57fb-f536-4122-9d8c-d8c60a6f773d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up/Down/Left/Right Arrow"",
                    ""id"": ""5610eb9a-0dc3-48c9-9c22-65a88f9c89f2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""1d843247-b1e6-4c95-a23a-d9f009f34a76"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""11701e74-2590-41ab-80a1-921d8d224a76"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""66c46a3d-f06d-4ad9-a042-05d044565347"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bfe31eed-bdac-4f2b-b6c0-25d4b92df513"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ArmToForward = m_Player.FindAction("ArmToForward", throwIfNotFound: true);
        m_Player_ArmToBack = m_Player.FindAction("ArmToBack", throwIfNotFound: true);
        m_Player_ArmToLeft = m_Player.FindAction("ArmToLeft", throwIfNotFound: true);
        m_Player_ArmToRight = m_Player.FindAction("ArmToRight", throwIfNotFound: true);
        m_Player_HandsCross = m_Player.FindAction("HandsCross", throwIfNotFound: true);
        m_Player_RaiseOnHand = m_Player.FindAction("RaiseOnHand", throwIfNotFound: true);
        m_Player_DeepSquat = m_Player.FindAction("DeepSquat", throwIfNotFound: true);
        m_Player_Butterfly = m_Player.FindAction("Butterfly", throwIfNotFound: true);
        m_Player_FastRun = m_Player.FindAction("FastRun", throwIfNotFound: true);
        m_Player_Freestyle = m_Player.FindAction("Freestyle", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        // Moat
        m_Moat = asset.FindActionMap("Moat", throwIfNotFound: true);
        m_Moat_ArmToForward = m_Moat.FindAction("ArmToForward", throwIfNotFound: true);
        m_Moat_ArmToBack = m_Moat.FindAction("ArmToBack", throwIfNotFound: true);
        m_Moat_ArmToLeft = m_Moat.FindAction("ArmToLeft", throwIfNotFound: true);
        m_Moat_ArmToRight = m_Moat.FindAction("ArmToRight", throwIfNotFound: true);
        m_Moat_HandsCross = m_Moat.FindAction("HandsCross", throwIfNotFound: true);
        m_Moat_RaiseOnHand = m_Moat.FindAction("RaiseOnHand", throwIfNotFound: true);
        m_Moat_PoseA = m_Moat.FindAction("PoseA", throwIfNotFound: true);
        m_Moat_PoseB = m_Moat.FindAction("PoseB", throwIfNotFound: true);
        m_Moat_PoseC = m_Moat.FindAction("PoseC", throwIfNotFound: true);
        m_Moat_PoseD = m_Moat.FindAction("PoseD", throwIfNotFound: true);
        m_Moat_LeftHandDrawCircle = m_Moat.FindAction("LeftHandDrawCircle", throwIfNotFound: true);
        m_Moat_RightHandDrawCircle = m_Moat.FindAction("RightHandDrawCircle", throwIfNotFound: true);
        m_Moat_SlideUp = m_Moat.FindAction("SlideUp", throwIfNotFound: true);
        m_Moat_SlideDown = m_Moat.FindAction("SlideDown", throwIfNotFound: true);
        m_Moat_SlideLeft = m_Moat.FindAction("SlideLeft", throwIfNotFound: true);
        m_Moat_SlideRight = m_Moat.FindAction("SlideRight", throwIfNotFound: true);
        m_Moat_Jump = m_Moat.FindAction("Jump", throwIfNotFound: true);
        m_Moat_SmallSquat = m_Moat.FindAction("SmallSquat", throwIfNotFound: true);
        m_Moat_Butterfly = m_Moat.FindAction("Butterfly", throwIfNotFound: true);
        m_Moat_FastRun = m_Moat.FindAction("FastRun", throwIfNotFound: true);
        m_Moat_LeanToLeft = m_Moat.FindAction("LeanToLeft", throwIfNotFound: true);
        m_Moat_LeanToRight = m_Moat.FindAction("LeanToRight", throwIfNotFound: true);
        m_Moat_Applaud = m_Moat.FindAction("Applaud", throwIfNotFound: true);
        m_Moat_Waving = m_Moat.FindAction("Waving", throwIfNotFound: true);
        m_Moat_Move = m_Moat.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ArmToForward;
    private readonly InputAction m_Player_ArmToBack;
    private readonly InputAction m_Player_ArmToLeft;
    private readonly InputAction m_Player_ArmToRight;
    private readonly InputAction m_Player_HandsCross;
    private readonly InputAction m_Player_RaiseOnHand;
    private readonly InputAction m_Player_DeepSquat;
    private readonly InputAction m_Player_Butterfly;
    private readonly InputAction m_Player_FastRun;
    private readonly InputAction m_Player_Freestyle;
    private readonly InputAction m_Player_Move;
    public struct PlayerActions
    {
        private @PlayerAction m_Wrapper;
        public PlayerActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArmToForward => m_Wrapper.m_Player_ArmToForward;
        public InputAction @ArmToBack => m_Wrapper.m_Player_ArmToBack;
        public InputAction @ArmToLeft => m_Wrapper.m_Player_ArmToLeft;
        public InputAction @ArmToRight => m_Wrapper.m_Player_ArmToRight;
        public InputAction @HandsCross => m_Wrapper.m_Player_HandsCross;
        public InputAction @RaiseOnHand => m_Wrapper.m_Player_RaiseOnHand;
        public InputAction @DeepSquat => m_Wrapper.m_Player_DeepSquat;
        public InputAction @Butterfly => m_Wrapper.m_Player_Butterfly;
        public InputAction @FastRun => m_Wrapper.m_Player_FastRun;
        public InputAction @Freestyle => m_Wrapper.m_Player_Freestyle;
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ArmToForward.started += instance.OnArmToForward;
            @ArmToForward.performed += instance.OnArmToForward;
            @ArmToForward.canceled += instance.OnArmToForward;
            @ArmToBack.started += instance.OnArmToBack;
            @ArmToBack.performed += instance.OnArmToBack;
            @ArmToBack.canceled += instance.OnArmToBack;
            @ArmToLeft.started += instance.OnArmToLeft;
            @ArmToLeft.performed += instance.OnArmToLeft;
            @ArmToLeft.canceled += instance.OnArmToLeft;
            @ArmToRight.started += instance.OnArmToRight;
            @ArmToRight.performed += instance.OnArmToRight;
            @ArmToRight.canceled += instance.OnArmToRight;
            @HandsCross.started += instance.OnHandsCross;
            @HandsCross.performed += instance.OnHandsCross;
            @HandsCross.canceled += instance.OnHandsCross;
            @RaiseOnHand.started += instance.OnRaiseOnHand;
            @RaiseOnHand.performed += instance.OnRaiseOnHand;
            @RaiseOnHand.canceled += instance.OnRaiseOnHand;
            @DeepSquat.started += instance.OnDeepSquat;
            @DeepSquat.performed += instance.OnDeepSquat;
            @DeepSquat.canceled += instance.OnDeepSquat;
            @Butterfly.started += instance.OnButterfly;
            @Butterfly.performed += instance.OnButterfly;
            @Butterfly.canceled += instance.OnButterfly;
            @FastRun.started += instance.OnFastRun;
            @FastRun.performed += instance.OnFastRun;
            @FastRun.canceled += instance.OnFastRun;
            @Freestyle.started += instance.OnFreestyle;
            @Freestyle.performed += instance.OnFreestyle;
            @Freestyle.canceled += instance.OnFreestyle;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ArmToForward.started -= instance.OnArmToForward;
            @ArmToForward.performed -= instance.OnArmToForward;
            @ArmToForward.canceled -= instance.OnArmToForward;
            @ArmToBack.started -= instance.OnArmToBack;
            @ArmToBack.performed -= instance.OnArmToBack;
            @ArmToBack.canceled -= instance.OnArmToBack;
            @ArmToLeft.started -= instance.OnArmToLeft;
            @ArmToLeft.performed -= instance.OnArmToLeft;
            @ArmToLeft.canceled -= instance.OnArmToLeft;
            @ArmToRight.started -= instance.OnArmToRight;
            @ArmToRight.performed -= instance.OnArmToRight;
            @ArmToRight.canceled -= instance.OnArmToRight;
            @HandsCross.started -= instance.OnHandsCross;
            @HandsCross.performed -= instance.OnHandsCross;
            @HandsCross.canceled -= instance.OnHandsCross;
            @RaiseOnHand.started -= instance.OnRaiseOnHand;
            @RaiseOnHand.performed -= instance.OnRaiseOnHand;
            @RaiseOnHand.canceled -= instance.OnRaiseOnHand;
            @DeepSquat.started -= instance.OnDeepSquat;
            @DeepSquat.performed -= instance.OnDeepSquat;
            @DeepSquat.canceled -= instance.OnDeepSquat;
            @Butterfly.started -= instance.OnButterfly;
            @Butterfly.performed -= instance.OnButterfly;
            @Butterfly.canceled -= instance.OnButterfly;
            @FastRun.started -= instance.OnFastRun;
            @FastRun.performed -= instance.OnFastRun;
            @FastRun.canceled -= instance.OnFastRun;
            @Freestyle.started -= instance.OnFreestyle;
            @Freestyle.performed -= instance.OnFreestyle;
            @Freestyle.canceled -= instance.OnFreestyle;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // Moat
    private readonly InputActionMap m_Moat;
    private List<IMoatActions> m_MoatActionsCallbackInterfaces = new List<IMoatActions>();
    private readonly InputAction m_Moat_ArmToForward;
    private readonly InputAction m_Moat_ArmToBack;
    private readonly InputAction m_Moat_ArmToLeft;
    private readonly InputAction m_Moat_ArmToRight;
    private readonly InputAction m_Moat_HandsCross;
    private readonly InputAction m_Moat_RaiseOnHand;
    private readonly InputAction m_Moat_PoseA;
    private readonly InputAction m_Moat_PoseB;
    private readonly InputAction m_Moat_PoseC;
    private readonly InputAction m_Moat_PoseD;
    private readonly InputAction m_Moat_LeftHandDrawCircle;
    private readonly InputAction m_Moat_RightHandDrawCircle;
    private readonly InputAction m_Moat_SlideUp;
    private readonly InputAction m_Moat_SlideDown;
    private readonly InputAction m_Moat_SlideLeft;
    private readonly InputAction m_Moat_SlideRight;
    private readonly InputAction m_Moat_Jump;
    private readonly InputAction m_Moat_SmallSquat;
    private readonly InputAction m_Moat_Butterfly;
    private readonly InputAction m_Moat_FastRun;
    private readonly InputAction m_Moat_LeanToLeft;
    private readonly InputAction m_Moat_LeanToRight;
    private readonly InputAction m_Moat_Applaud;
    private readonly InputAction m_Moat_Waving;
    private readonly InputAction m_Moat_Move;
    public struct MoatActions
    {
        private @PlayerAction m_Wrapper;
        public MoatActions(@PlayerAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @ArmToForward => m_Wrapper.m_Moat_ArmToForward;
        public InputAction @ArmToBack => m_Wrapper.m_Moat_ArmToBack;
        public InputAction @ArmToLeft => m_Wrapper.m_Moat_ArmToLeft;
        public InputAction @ArmToRight => m_Wrapper.m_Moat_ArmToRight;
        public InputAction @HandsCross => m_Wrapper.m_Moat_HandsCross;
        public InputAction @RaiseOnHand => m_Wrapper.m_Moat_RaiseOnHand;
        public InputAction @PoseA => m_Wrapper.m_Moat_PoseA;
        public InputAction @PoseB => m_Wrapper.m_Moat_PoseB;
        public InputAction @PoseC => m_Wrapper.m_Moat_PoseC;
        public InputAction @PoseD => m_Wrapper.m_Moat_PoseD;
        public InputAction @LeftHandDrawCircle => m_Wrapper.m_Moat_LeftHandDrawCircle;
        public InputAction @RightHandDrawCircle => m_Wrapper.m_Moat_RightHandDrawCircle;
        public InputAction @SlideUp => m_Wrapper.m_Moat_SlideUp;
        public InputAction @SlideDown => m_Wrapper.m_Moat_SlideDown;
        public InputAction @SlideLeft => m_Wrapper.m_Moat_SlideLeft;
        public InputAction @SlideRight => m_Wrapper.m_Moat_SlideRight;
        public InputAction @Jump => m_Wrapper.m_Moat_Jump;
        public InputAction @SmallSquat => m_Wrapper.m_Moat_SmallSquat;
        public InputAction @Butterfly => m_Wrapper.m_Moat_Butterfly;
        public InputAction @FastRun => m_Wrapper.m_Moat_FastRun;
        public InputAction @LeanToLeft => m_Wrapper.m_Moat_LeanToLeft;
        public InputAction @LeanToRight => m_Wrapper.m_Moat_LeanToRight;
        public InputAction @Applaud => m_Wrapper.m_Moat_Applaud;
        public InputAction @Waving => m_Wrapper.m_Moat_Waving;
        public InputAction @Move => m_Wrapper.m_Moat_Move;
        public InputActionMap Get() { return m_Wrapper.m_Moat; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoatActions set) { return set.Get(); }
        public void AddCallbacks(IMoatActions instance)
        {
            if (instance == null || m_Wrapper.m_MoatActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MoatActionsCallbackInterfaces.Add(instance);
            @ArmToForward.started += instance.OnArmToForward;
            @ArmToForward.performed += instance.OnArmToForward;
            @ArmToForward.canceled += instance.OnArmToForward;
            @ArmToBack.started += instance.OnArmToBack;
            @ArmToBack.performed += instance.OnArmToBack;
            @ArmToBack.canceled += instance.OnArmToBack;
            @ArmToLeft.started += instance.OnArmToLeft;
            @ArmToLeft.performed += instance.OnArmToLeft;
            @ArmToLeft.canceled += instance.OnArmToLeft;
            @ArmToRight.started += instance.OnArmToRight;
            @ArmToRight.performed += instance.OnArmToRight;
            @ArmToRight.canceled += instance.OnArmToRight;
            @HandsCross.started += instance.OnHandsCross;
            @HandsCross.performed += instance.OnHandsCross;
            @HandsCross.canceled += instance.OnHandsCross;
            @RaiseOnHand.started += instance.OnRaiseOnHand;
            @RaiseOnHand.performed += instance.OnRaiseOnHand;
            @RaiseOnHand.canceled += instance.OnRaiseOnHand;
            @PoseA.started += instance.OnPoseA;
            @PoseA.performed += instance.OnPoseA;
            @PoseA.canceled += instance.OnPoseA;
            @PoseB.started += instance.OnPoseB;
            @PoseB.performed += instance.OnPoseB;
            @PoseB.canceled += instance.OnPoseB;
            @PoseC.started += instance.OnPoseC;
            @PoseC.performed += instance.OnPoseC;
            @PoseC.canceled += instance.OnPoseC;
            @PoseD.started += instance.OnPoseD;
            @PoseD.performed += instance.OnPoseD;
            @PoseD.canceled += instance.OnPoseD;
            @LeftHandDrawCircle.started += instance.OnLeftHandDrawCircle;
            @LeftHandDrawCircle.performed += instance.OnLeftHandDrawCircle;
            @LeftHandDrawCircle.canceled += instance.OnLeftHandDrawCircle;
            @RightHandDrawCircle.started += instance.OnRightHandDrawCircle;
            @RightHandDrawCircle.performed += instance.OnRightHandDrawCircle;
            @RightHandDrawCircle.canceled += instance.OnRightHandDrawCircle;
            @SlideUp.started += instance.OnSlideUp;
            @SlideUp.performed += instance.OnSlideUp;
            @SlideUp.canceled += instance.OnSlideUp;
            @SlideDown.started += instance.OnSlideDown;
            @SlideDown.performed += instance.OnSlideDown;
            @SlideDown.canceled += instance.OnSlideDown;
            @SlideLeft.started += instance.OnSlideLeft;
            @SlideLeft.performed += instance.OnSlideLeft;
            @SlideLeft.canceled += instance.OnSlideLeft;
            @SlideRight.started += instance.OnSlideRight;
            @SlideRight.performed += instance.OnSlideRight;
            @SlideRight.canceled += instance.OnSlideRight;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @SmallSquat.started += instance.OnSmallSquat;
            @SmallSquat.performed += instance.OnSmallSquat;
            @SmallSquat.canceled += instance.OnSmallSquat;
            @Butterfly.started += instance.OnButterfly;
            @Butterfly.performed += instance.OnButterfly;
            @Butterfly.canceled += instance.OnButterfly;
            @FastRun.started += instance.OnFastRun;
            @FastRun.performed += instance.OnFastRun;
            @FastRun.canceled += instance.OnFastRun;
            @LeanToLeft.started += instance.OnLeanToLeft;
            @LeanToLeft.performed += instance.OnLeanToLeft;
            @LeanToLeft.canceled += instance.OnLeanToLeft;
            @LeanToRight.started += instance.OnLeanToRight;
            @LeanToRight.performed += instance.OnLeanToRight;
            @LeanToRight.canceled += instance.OnLeanToRight;
            @Applaud.started += instance.OnApplaud;
            @Applaud.performed += instance.OnApplaud;
            @Applaud.canceled += instance.OnApplaud;
            @Waving.started += instance.OnWaving;
            @Waving.performed += instance.OnWaving;
            @Waving.canceled += instance.OnWaving;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(IMoatActions instance)
        {
            @ArmToForward.started -= instance.OnArmToForward;
            @ArmToForward.performed -= instance.OnArmToForward;
            @ArmToForward.canceled -= instance.OnArmToForward;
            @ArmToBack.started -= instance.OnArmToBack;
            @ArmToBack.performed -= instance.OnArmToBack;
            @ArmToBack.canceled -= instance.OnArmToBack;
            @ArmToLeft.started -= instance.OnArmToLeft;
            @ArmToLeft.performed -= instance.OnArmToLeft;
            @ArmToLeft.canceled -= instance.OnArmToLeft;
            @ArmToRight.started -= instance.OnArmToRight;
            @ArmToRight.performed -= instance.OnArmToRight;
            @ArmToRight.canceled -= instance.OnArmToRight;
            @HandsCross.started -= instance.OnHandsCross;
            @HandsCross.performed -= instance.OnHandsCross;
            @HandsCross.canceled -= instance.OnHandsCross;
            @RaiseOnHand.started -= instance.OnRaiseOnHand;
            @RaiseOnHand.performed -= instance.OnRaiseOnHand;
            @RaiseOnHand.canceled -= instance.OnRaiseOnHand;
            @PoseA.started -= instance.OnPoseA;
            @PoseA.performed -= instance.OnPoseA;
            @PoseA.canceled -= instance.OnPoseA;
            @PoseB.started -= instance.OnPoseB;
            @PoseB.performed -= instance.OnPoseB;
            @PoseB.canceled -= instance.OnPoseB;
            @PoseC.started -= instance.OnPoseC;
            @PoseC.performed -= instance.OnPoseC;
            @PoseC.canceled -= instance.OnPoseC;
            @PoseD.started -= instance.OnPoseD;
            @PoseD.performed -= instance.OnPoseD;
            @PoseD.canceled -= instance.OnPoseD;
            @LeftHandDrawCircle.started -= instance.OnLeftHandDrawCircle;
            @LeftHandDrawCircle.performed -= instance.OnLeftHandDrawCircle;
            @LeftHandDrawCircle.canceled -= instance.OnLeftHandDrawCircle;
            @RightHandDrawCircle.started -= instance.OnRightHandDrawCircle;
            @RightHandDrawCircle.performed -= instance.OnRightHandDrawCircle;
            @RightHandDrawCircle.canceled -= instance.OnRightHandDrawCircle;
            @SlideUp.started -= instance.OnSlideUp;
            @SlideUp.performed -= instance.OnSlideUp;
            @SlideUp.canceled -= instance.OnSlideUp;
            @SlideDown.started -= instance.OnSlideDown;
            @SlideDown.performed -= instance.OnSlideDown;
            @SlideDown.canceled -= instance.OnSlideDown;
            @SlideLeft.started -= instance.OnSlideLeft;
            @SlideLeft.performed -= instance.OnSlideLeft;
            @SlideLeft.canceled -= instance.OnSlideLeft;
            @SlideRight.started -= instance.OnSlideRight;
            @SlideRight.performed -= instance.OnSlideRight;
            @SlideRight.canceled -= instance.OnSlideRight;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @SmallSquat.started -= instance.OnSmallSquat;
            @SmallSquat.performed -= instance.OnSmallSquat;
            @SmallSquat.canceled -= instance.OnSmallSquat;
            @Butterfly.started -= instance.OnButterfly;
            @Butterfly.performed -= instance.OnButterfly;
            @Butterfly.canceled -= instance.OnButterfly;
            @FastRun.started -= instance.OnFastRun;
            @FastRun.performed -= instance.OnFastRun;
            @FastRun.canceled -= instance.OnFastRun;
            @LeanToLeft.started -= instance.OnLeanToLeft;
            @LeanToLeft.performed -= instance.OnLeanToLeft;
            @LeanToLeft.canceled -= instance.OnLeanToLeft;
            @LeanToRight.started -= instance.OnLeanToRight;
            @LeanToRight.performed -= instance.OnLeanToRight;
            @LeanToRight.canceled -= instance.OnLeanToRight;
            @Applaud.started -= instance.OnApplaud;
            @Applaud.performed -= instance.OnApplaud;
            @Applaud.canceled -= instance.OnApplaud;
            @Waving.started -= instance.OnWaving;
            @Waving.performed -= instance.OnWaving;
            @Waving.canceled -= instance.OnWaving;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(IMoatActions instance)
        {
            if (m_Wrapper.m_MoatActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMoatActions instance)
        {
            foreach (var item in m_Wrapper.m_MoatActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MoatActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MoatActions @Moat => new MoatActions(this);
    public interface IPlayerActions
    {
        void OnArmToForward(InputAction.CallbackContext context);
        void OnArmToBack(InputAction.CallbackContext context);
        void OnArmToLeft(InputAction.CallbackContext context);
        void OnArmToRight(InputAction.CallbackContext context);
        void OnHandsCross(InputAction.CallbackContext context);
        void OnRaiseOnHand(InputAction.CallbackContext context);
        void OnDeepSquat(InputAction.CallbackContext context);
        void OnButterfly(InputAction.CallbackContext context);
        void OnFastRun(InputAction.CallbackContext context);
        void OnFreestyle(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
    public interface IMoatActions
    {
        void OnArmToForward(InputAction.CallbackContext context);
        void OnArmToBack(InputAction.CallbackContext context);
        void OnArmToLeft(InputAction.CallbackContext context);
        void OnArmToRight(InputAction.CallbackContext context);
        void OnHandsCross(InputAction.CallbackContext context);
        void OnRaiseOnHand(InputAction.CallbackContext context);
        void OnPoseA(InputAction.CallbackContext context);
        void OnPoseB(InputAction.CallbackContext context);
        void OnPoseC(InputAction.CallbackContext context);
        void OnPoseD(InputAction.CallbackContext context);
        void OnLeftHandDrawCircle(InputAction.CallbackContext context);
        void OnRightHandDrawCircle(InputAction.CallbackContext context);
        void OnSlideUp(InputAction.CallbackContext context);
        void OnSlideDown(InputAction.CallbackContext context);
        void OnSlideLeft(InputAction.CallbackContext context);
        void OnSlideRight(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSmallSquat(InputAction.CallbackContext context);
        void OnButterfly(InputAction.CallbackContext context);
        void OnFastRun(InputAction.CallbackContext context);
        void OnLeanToLeft(InputAction.CallbackContext context);
        void OnLeanToRight(InputAction.CallbackContext context);
        void OnApplaud(InputAction.CallbackContext context);
        void OnWaving(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
    }
}
