.build: &build
  stage: build stardust
  image: ccr.ccs.tencentyun.com/solution/go-gcc-mingw-w64:0.1
  needs: 
    - build:prepare

build:reverie:
  <<: *build
  before_script:
    - cd reverie
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod tidy
    - CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o main.exe main.go
    - chmod +x pack.sh
    - ./pack.sh
    - mv reverie.tar.gz ../reverie.tar.gz
  artifacts:
    paths:
      - reverie.tar.gz