.build: &build
  stage: build stardust
  image: ccr.ccs.tencentyun.com/solution/go-gcc-mingw-w64:0.1
  needs: 
    - build:prepare

build:reverie:
  <<: *build
  before_script:
    - cd reverie
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod tidy
    - CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o main.exe main.go
    - chmod +x pack.sh
    - ./pack.sh
    - mv reverie.tar.gz ../reverie.tar.gz
  artifacts:
    paths:
      - reverie.tar.gz

release:reverie:
  stage: release 
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - echo 'running release_job'
    - echo 'Previous Job ID is printed below'
    - echo $GE_JOB_ID
    - echo "Publishing artifacts to release ${CI_COMMIT_TAG}..."
  needs: 
    - job: build:reverie
      artifacts: true
  release:
    name: '${CI_COMMIT_TAG}'
    description: 'Created using the release-cli'
    tag_name: '${CI_COMMIT_TAG}'
    assets:
      links:
        - name: 'stardust-${CI_COMMIT_TAG}'
          url: 'https://gitlab.deepglint.com/alpha/dipper/-/jobs/${GE_JOB_ID}/artifacts/download'
  rules:
    - if: $CI_COMMIT_TAG

release:push:
  stage: release
  image: 
    name: ccr.ccs.tencentyun.com/solution/python-gitlab:v3.15.0
    entrypoint: [""]
  script:
    - pip install --trusted-host package.nemoface.com -i http://package.nemoface.com/repository/pypi/simple gitbot
    - git-release
  needs:
    - job: release:reverie
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG