.build: &build
  stage: build stardust
  image: golang:1.20.6-bullseye
  needs: 
    - build:prepare

build:reverie:
  <<: *build
  before_script:
    - cd reverie
  script:
    - apt update
    - apt-get install -y gcc-mingw-w64-x86-64
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod tidy
    - CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -o main.exe main.go
    - chmod +x pack.sh
    - ./pack.sh
    - mv reverie.tar.gz ../
  artifacts:
    paths:
      - reverie.tar.gz
    reports:
      dotenv: reverie.env

